sudo: required
services:
  - docker

before_install:
  - docker build -t zhaoshuosve/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=tru zhaoshuosve/react-test npm run test -- --coverage

after_success:
  - docker build -t zhaoshuosve/multi-client ./client
  - docker build -t zhaoshuosve/multi-nginx ./nginx
  - docker build -t zhaoshuosve/multi-server ./server
  - docker build -t zhaoshuosve/multi-worker ./worker

  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take docker images and push them to docker hub
  - docker push zhaoshuosve/multi-client
  - docker push zhaoshuosve/multi-nginx
  - docker push zhaoshuosve/multi-server
  - docker push zhaoshuosve/multi-worker